% This is an autogenerated sample test for rockPaperScissors
classdef rockPaperScissorsTest < matlab.unittest.TestCase
    methods (Test)
        function testRockPaperScissors(testCase)
            % Specify the inputs
            player1Choice = "rock";
            player2Choice = "scissors";

            % Exercise the code
            actualOutput_result = rockPaperScissors(player1Choice, player2Choice);

            % Specify the expected outputs
            expectedOutput_result = "Player 1 wins";

            % Verify the result
            testCase.verifyEqual(actualOutput_result, expectedOutput_result);
        end
    end
end